# -*- coding: utf-8 -*-

import json
import csv
import sys

print "usage: python (output_02152017.json) (output_02152017.csv)"

#takes the first argument after the script from the command line and open the json file
new = open(sys.argv[1])
#takes the second argument which corresponds to the name of the new file, the destination csv file
with open(sys.argv[2], 'wb') as f:
    #Return a writer object responsible for converting the user’s data into delimited strings on the given file-like object.
    #Delimiter: A one-character string used to separate fields.
    #Quotechar: A one-character string used to quote fields containing special characters, such as the delimiter or quotechar, or which contain new-line characters. It defaults to '"'
    #Quoting: Controls when quotes should be generated by the writer and recognised by the reader.
    writer = csv.writer(f,delimiter=';', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    #Loop for read each tweet from json
    for line in new:
        #Loads a single tweet in this iteration
        data=json.loads(line)
        #try -- except for error handling
        try:
            #Object with fields from json to be written in the csv file
            row =(data["created_at"],"@"+data["user"]["screen_name"],data['text'].encode('utf-8'))
            #Writes new row on csv file
            writer.writerow(row)
            #Display currently written row
            print row
        except IOError as e:
            print "I/O error({0}): {1}".format(e.errno, e.strerror)